config/routes.rb
Rails.application.routes.draw do
    root to: 'pages#home'
    devise_for :users, controllers: {registrations: 'users/registrations' }
    resources :users do
        resource :profile
    end
    get 'about', to: 'pages#about'
    resources :contacts, only: :create
    get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    #Contact form validations.
    validates :name, presence: true
    validates :email, presence: true
    validates :comments, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
   belongs_to :user 
   has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
   validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
  belongs_to :plan
  has_one :profile
  
  attr_accessor :stripe_card_token
  def save_with_subscription
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
 before_action :configure_permitted_parameters, if: :devise_controller?
protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation) }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
    #GET request to /contact-us
    #Show new contact form
    def new
        @contact = Contact.new
    end
    
    #POST request to /contacts
    def create
            #Mass assginment of form fileds into contact objects.
            @contact = Contact.new(contact_params)
            #Save the form object to the database.
            if @contact.save
                #Store form fields via parameters, into variables.
                name = params[:contact][:name]
                email = params[:contact][:email]
                body = params[:contact][:comments]
                #Plug variables into Contact Mailer.
                #email method and send Email.
                ContactMailer.contact_email(name, email, body).deliver
                #Store success message in flash hash
                flash[:success] = "Message on the way somewhere."
            else
                #If Contact object doesnt save, store errors in flash hash,
                flash[:danger] = @contact.errors.full_messages.join(", ")
            end
            redirect_to new_contact_path
    end
    private
    #To collect data from form we need to use strong parameters
    #and whitelist the form fields.
      def contact_params
         params.require(:contact).permit(:name, :email, :comments)
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    #Get request for / which is our home page.
    def Home
        @basic_plan = Plan.find(1)
        @pro_plan = Plan.find(2)
    end

    def About
    end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
   before_action :authenticate_user!
   before_action :only_current_user

   #GET to /user/:user.id/profile/new
   def new
    @profile = Profile.new
   end
    
    #POST to /users/:user_id/profile
   def create
    @user = User.find(params[:user_id])
    @profile = @user.build_profile( profile_params)
     if @profile.save
      flash[:success] = "Profile updated"
      redirect_to user_path( params[:user_id] )
     else
      render action :new
     end
   end

   #Get to /users/:user_id/profile/edit
   def edit
    @user = User.find(params[:user_id])
    @profile = @user.profile 
   end
   
   #Put to /users/:user_id/profile/
   def update
    @user = User.find(params[:user_id])
    @profile = @user.profile
    if @profile.update_attributes(profile_params)
     flash[:success] = "Profile updated"
     redirect_to user_path(id: params[:user_id] ) 
    else
      render action :edit
    end
   end
   
   private
    def profile_params
        params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
    end

    def only_current_user
      @user = User.find( params[:user_id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
  before_action :select_plan, only: :new
  
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_subscription
        else
          resource.save
        end
      end
    end
  end
  
  private
  def select_plan
    unless (params[:plan] == '1' || params[:plan] == '2')
    flash[:notice] = 'Please select a membership plan to signup.'
    redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!

   def index
   	@users = User.includes(:profile)
   end

   #GET request to users/:id
   def show
    @user = User.find( params[:id] )
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
    <div class= "row">
        <h1 class="text-center">Talk to us</h1>
        
        <div class= "col-md-4  col-md-offset-4 text-center">
            <div class= "well">
              <%= form_for @contact do |f| %>
                <div class= "form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
            
                <div class= "form-group">
                    <%= f.label :email %>
                    <%= f.text_field :email, class: 'form-control' %>
                </div>
                
                <div class= "form-group">
                    <%= f.label :comments %>
                    <%= f.text_area :comments, class: 'form-control' %>
                </div>
                
                <%= f.submit 'Submit', class: "btn btn-default" %>
              <% end %>
          </div>
      </div>
  </div>
<div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.stripe.com/v2/', type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  </head>

  <body>
        <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-fire"></i>
            FireFight
            
            <%end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete%></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Community", users_path %> </li>
              <li><%= link_to "My Account", edit_user_registration_path %> </li>
            <% end %>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact Us", new_contact_path %></li>

          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
          <div class= "container flash-container"> 
               <div class= "text-center">
                 <% flash.each do|type, msg|  %>
                 </div>
                 <%= content_tag :div, msg, class: "alert alert-#{type}" %>
               <% end %>
          </div>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class= "container text-center">
    <h1>About Us</h1>
    <p>A place for like minded firearm enthusiasts to meet and share ideas and hook up on sweet training courses.</p>
</div>

app/views/pages/home.html.erb
<div class= "home-callout text-center container-fluid">
    <h1>Welcome to FireFight</h1>
    <h3>A membership site for firearm training enthusiasts.</h3>
</div>    

<div class= "container-fluid home-signup-links">
<% if user_signed_in? %>
  <div class="col-md-6">
    <div class="well"> 
      <h2 class="text-center">Your Profile</h2>
        <% if current_user.profile %>
          <%= link_to "Edit your profile", edit_user_profile_path(user_id: current_user.id) , class:'btn btn-default btn-lg btn-block' %>
          <%= link_to "View your profile", user_path(id: current_user.id), class: 'btn btn-default btn-large btn-block' %>
        <% else %>
         <p> Create a profile to interact with the community.</p>
         <%= link_to "create your profile here", new_user_profile_path(user_id: current_user.id), class:'btn btn-default btn-lg btn-block' %>
         <% end %>
    </div>
  </div>
    <div class="col-md-6">
      <div class="well"> 
        <h2 class="text-center">The Community</h2>
        <p>Visit the community to meet other like minded enthusiasts.</p>
        <%= link_to "Visit the community", users_path , class:'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
<% else %>
      <div class= "row">
        <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Basic Membership</h2>
          <h4>Sign up for free and get basic access to the community <br>.</h4>
          <%= link_to "Sign up with Basic", new_user_registration_path(plan: Plan.find(1).id), class: 'btn btn-primary btn-lg btn-block' %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Pro Membership</h2>
          <h4>Sign up for the pro account for $10/month and get access to the community and contact information!</h4>
          <%= link_to "Sign up with Pro", new_user_registration_path(plan: Plan.find(2).id), class: 'btn btn-success btn-lg btn-block' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Instructor', 'Student'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
	<div class="row">
	     <div class="col-md-6 col-md-offset-3">
		    <h1 class="text-center">Edit Your Profile</h1>
		    <p class="text-center">Be a part of the FireFight community and fill out your profile!</p>
		   <div class="well">
	     	<%= render 'form' %>
	    </div>
	  </div>
	</div>
</div>

app/views/profiles/new.html.erb
<div class="container">
	<div class="row">
	     <div class="col-md-6 col-md-offset-3">
		    <h1 class="text-center">Create Your Profile</h1>
		    <p class="text-center">Be a part of the FireFight community and fill out your profile!</p>
		    <div class="well">
	     	<%= render 'form' %>
	    </div>
	  </div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1 class='text-center'> FireFight Community</h1>
			<p class='text-center'>Welcome to the FireFight Community. Users need to have a filled out profile before they are visible.</p>
			<ul class="list-unstyled">
				<% @users.each do |user| %>
					<% if user.profile %>
					 <li>
						<div class="well row <%= cycle('white-bg', '') %>">
						 	<div class="col-sm-4 text-center">
						 		<% if user.profile.avatar %>
						 		 <%= link_to user do %>
						 			<%= image_tag user.profile.avatar.url, class: 'user-index-avatar' %>
						 		 <% end %>
						 		<% end %>
						 	</div>
						 	<div>
						 		<%= link_to user do %>
						 		<h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
						 		<% end %>
						 		<p><%= user.profile.job_title %>
						 			<% if user.plan_id ==2 %>
						 			<span class="label label-danger">PRO</span>
						 			<% end %>
						 		</p>

						</div>
					 </li>
					<% end %>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 text-center">
      <%= image_tag @user.profile.avatar.url, class:'avatar-img' %>
    </div>

    <div class="col-md-6">
     <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
     <h3><%= @user.profile.job_title %></h3><br/>
      	<div class="well profile-block profile-description">
      		<h3>Description</h3>
        	<%= @user.profile.description %>
      	</div>
      <% if true #current_user.plan_id == 2 %>
     	<div class="well profile-block profile-contact-info">
     		<h3>Contact Info</h3>
         	<%= @user.profile.phone_number %><br/>
        	<%= @user.profile.contact_email %> <br/>
     	</div>  
      <% end %>
     </div>
  </div>
</div>